# Generated by Django 4.2.11 on 2024-03-29 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('medicine', models.ManyToManyField(through='medicine.Effect', to='medicine.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='effect',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine'),
        ),
        migrations.AddField(
            model_name='effect',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.symptom'),
        ),
        migrations.AlterUniqueTogether(
            name='effect',
            unique_together={('medicine', 'symptom')},
        ),
    ]
